/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dispatcher;

import configuration.animation;
import configuration.config;
import dispatcher.AllOrders.allOrders;
import dispatcher.delivered.deliveredPanel;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;
import javax.swing.ButtonGroup;

/**
 *
 * @author user
 */
public class DispatcherDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dispatcher
     */
    public DispatcherDashboard() {
        initComponents();
        toggleButtons();
        ShowParcelCount();
    }
    
    public void toggleButtons(){
        ButtonGroup menuGroup = new ButtonGroup();
        animation ani = new animation();
        
        menuGroup.add(pend);
        menuGroup.add(delivered);
        menuGroup.add(totalOrders);
        
        ani.StyleToggleButtons(pend); 
        ani.StyleToggleButtons(delivered); 
        ani.StyleToggleButtons(totalOrders); 
    }       
    
    public void ShowParcelCount() {
    config conf = new config();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    java.util.Date now = new java.util.Date();

    int totalOrders = 0;
    int pendingCount = 0;         // Delivered Parcels
    int inTransitCount = 0;       // Pending Parcels
    int deliveryInProgressCount = 0;
    int completedCount = 0;
    int toBeDeliveredCount = 0;   // Orders pending delivery

    // Fetch all exports
    String query = "SELECT export_status, date_export, export_id FROM exports";
    List<Map<String, Object>> orders = conf.fetchRecords(query);

    for (Map<String, Object> order : orders) {
        String currentStatus = order.get("export_status").toString();
        String dateStr = order.get("date_export").toString();
        java.util.Date exportDate;

        try {
            exportDate = sdf.parse(dateStr);
        } catch (Exception e) {
            System.out.println("Error parsing date for export ID " + order.get("export_id") + ": " + dateStr);
            continue;
        }

        long diffDays = (now.getTime() - exportDate.getTime()) / (1000 * 60 * 60 * 24); // difference in days
        String newStatus = currentStatus;

        totalOrders++;

        switch (currentStatus) {
            case "In Transit":
                if (diffDays >= 4) {
                    newStatus = "On Delivery"; // change status if in transit for 4+ days
                    deliveryInProgressCount++;
                    toBeDeliveredCount++;
                } else {
                    inTransitCount++;
                    toBeDeliveredCount++;
                }
                break;

            case "On Delivery":
                deliveryInProgressCount++;
                toBeDeliveredCount++;
                break;

            case "Delivered":
                completedCount++;
                pendingCount++;
                break;

            default: // Pending or unknown
                toBeDeliveredCount++;
                break;
        }

        // Update DB if status has changed
        if (!newStatus.equals(currentStatus)) {
            String updateQry = "UPDATE exports SET export_status = ? WHERE export_id = ?";
            conf.updateRecord(updateQry, newStatus, order.get("export_id"));
        }
    }

    // Update GUI labels
    parcels.setText(totalOrders + " Total Parcels");
    comp.setText(completedCount + " Delivered Parcels");
    pendings.setText(deliveryInProgressCount + " Pending Parcels");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pend = new javax.swing.JToggleButton();
        delivered = new javax.swing.JToggleButton();
        pendings = new javax.swing.JLabel();
        parcels = new javax.swing.JLabel();
        comp = new javax.swing.JLabel();
        totalOrders = new javax.swing.JToggleButton();
        MainPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setText("ARMEX");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setText("DISPATCHING");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setText("PANEL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        pend.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        pend.setSelected(true);
        pend.setText("PENDING PARCELS");
        pend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendMouseClicked(evt);
            }
        });
        jPanel1.add(pend, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 210, 60));

        delivered.setText("DELIVERED");
        delivered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveredMouseClicked(evt);
            }
        });
        jPanel1.add(delivered, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, 60));

        pendings.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        pendings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendings.setText("PENDINGS");
        pendings.setOpaque(true);
        jPanel1.add(pendings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 50));

        parcels.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        parcels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        parcels.setText("PARCELS");
        parcels.setOpaque(true);
        jPanel1.add(parcels, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 50));

        comp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        comp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comp.setText("COMPLETED");
        comp.setOpaque(true);
        jPanel1.add(comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 50));

        totalOrders.setText("ALL ORDERS");
        totalOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalOrdersMouseClicked(evt);
            }
        });
        jPanel1.add(totalOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 210, 60));

        javax.swing.GroupLayout MainPaneLayout = new javax.swing.GroupLayout(MainPane);
        MainPane.setLayout(MainPaneLayout);
        MainPaneLayout.setHorizontalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 976, Short.MAX_VALUE)
        );
        MainPaneLayout.setVerticalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendMouseClicked
        PendingParcels pend = new PendingParcels(MainPane);
        MainPane.add(pend).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_pendMouseClicked

    private void deliveredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveredMouseClicked
        deliveredPanel deli = new deliveredPanel(MainPane);
        MainPane.add(deli).setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_deliveredMouseClicked

    private void totalOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalOrdersMouseClicked
        allOrders ord = new allOrders();

        MainPane.add(ord).setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_totalOrdersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DispatcherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DispatcherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DispatcherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DispatcherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DispatcherDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MainPane;
    private javax.swing.JLabel comp;
    private javax.swing.JToggleButton delivered;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel parcels;
    private javax.swing.JToggleButton pend;
    private javax.swing.JLabel pendings;
    private javax.swing.JToggleButton totalOrders;
    // End of variables declaration//GEN-END:variables
}
