/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dispatcher;

import Admin.ProductControl.Refactor_Product;
import Admin.ProductControl.connector;
import configuration.config;
import javax.swing.JDesktopPane;

/**
 *
 * @author user
 */
public final class pendingParcelsTable extends javax.swing.JInternalFrame {

    /**
     * Creates new form pendingParcelsTable
     */
    private JDesktopPane parcelPane;
    private JDesktopPane tablePane;
    
    public pendingParcelsTable(JDesktopPane parcel, JDesktopPane table) {
        this.parcelPane = parcel;
        this.tablePane = table;
        
        initComponents();
        DisplayParcels();
        StyleFrame();
        StyleTable();
    }
    
    public final void StyleFrame(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.plaf.basic.BasicInternalFrameUI ui =
            (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
    
    public final void StyleTable(){
        table.setRowHeight(40);
    }
    
    public void DisplayParcels(){
        config conf = new config();
        
        String qry = "SELECT export_id, reference_number, export_status, export_reciever FROM exports WHERE export_status = 'Pending'";
        conf.displayData(qry, table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();
        
        Object ref = table.getValueAt(row, 1);
        Object id = table.getValueAt(row, 0);
            System.out.println("Selected ID: " + id);
            
            String refNum = (String) ref;
            
            parcelPane.removeAll();
            pendingParcelPanel panel = new pendingParcelPanel(refNum);
            parcelPane.add(panel).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
