/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.userOrders;

import Admin.ProductControl.Refactor_Product;
import Admin.ProductControl.connector;
import Profiles.session;
import configuration.config;
import javax.swing.JDesktopPane;

/**
 *
 * @author user
 */
public class DisplayTable extends javax.swing.JInternalFrame {

    /**
     * Creates new form DisplayTable
     */
    private final String stat;
    private final String selected;
    private String text;
    private JDesktopPane MiniPanel;
    
    public DisplayTable(String status, String searchSelected, String searchText, JDesktopPane panel) {
        this.stat = status;
        this.selected = searchSelected;
        this.text = searchText;
        this.MiniPanel = panel;
        
        initComponents();
        DispTable();
        StyleFrame();
        StyleTable();
    }
    
    public final void StyleTable(){
        table.setRowHeight(40);
    }
    
    public final void StyleFrame(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.plaf.basic.BasicInternalFrameUI ui =
            (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
    
    public void DispTable() {
        config conf = new config();
        session see = new session();

        String q = "SELECT order_id, prod_id, user_id, order_status FROM userOrders";
        boolean hasWhere = false;

        // 1️⃣ Filter by status if not All
        if(stat != null && !stat.equalsIgnoreCase("All")) {
            q += " WHERE order_status = '" + stat.replace("'", "''") + "'";
            hasWhere = true;
        }

        // 2️⃣ Only filter by selected+text if BOTH are provided AND text is not placeholder
        boolean validText = text != null && !text.trim().isEmpty()
                            && !text.equalsIgnoreCase("Search User ID . . .")
                            && !text.equalsIgnoreCase("Search Product ID . . .")
                            && !text.equalsIgnoreCase("Search Order ID . . .");

        boolean validColumn = selected != null && !selected.isEmpty();

        if(validText && validColumn) {
            text = text.trim().replace("'", "''"); // trim + escape
            if(selected.equals("order_id") || selected.equals("prod_id") || selected.equals("user_id")) {
                if(hasWhere) q += " AND CAST(" + selected + " AS TEXT) LIKE '%" + text + "%'";
                else q += " WHERE CAST(" + selected + " AS TEXT) LIKE '%" + text + "%'";
            }
        }

        System.out.println("Final Query: " + q);
        conf.displayData(q, table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();

        Object id = table.getValueAt(row, 0);
        System.out.println("Selected ID: " + id);
        
        int FinalId = (int) id;

        export ex = new export(FinalId);
        MiniPanel.add(ex).setVisible(true);
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
