/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.userOrders;

import Admin.Admin_config;
import Profiles.session;
import configuration.animation;
import configuration.config;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Map;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public final class uOrders extends javax.swing.JInternalFrame {

    /**
     * Creates new form uOrders
     */
    private String s;
    
    public uOrders() {
        Admin_config admin = new Admin_config();
        
        initComponents();
        admin.DisplayStatusAction(status);
        disp();
        admin.DisplaySearchAction(searchBox);
        StyleFrame();
        s = "Search User ID . . .";
        countIndicators();
    }
    
    public void countIndicators() {
        config conf = new config();
        try {
            // 1️⃣ Count pending orders
            String pendingQuery = "SELECT COUNT(*) AS cnt FROM userOrders WHERE order_status = 'Pending'";
            java.util.List<java.util.Map<String, Object>> pendingResult = conf.fetchRecords(pendingQuery);

            int pendingCount = 0;
            if (!pendingResult.isEmpty()) {
                pendingCount = Integer.parseInt(pendingResult.get(0).get("cnt").toString());
            }

            // 2️⃣ Count total orders
            String totalQuery = "SELECT COUNT(*) AS cnt FROM userOrders";
            java.util.List<java.util.Map<String, Object>> totalResult = conf.fetchRecords(totalQuery);

            int totalCount = 0;
            if (!totalResult.isEmpty()) {
                totalCount = Integer.parseInt(totalResult.get(0).get("cnt").toString());
            }

            // 3️⃣ Update labels
            pending.setText(String.valueOf(pendingCount) + " Pending Orders");
            pending.setForeground(Color.decode("#006307"));
            orders.setText(String.valueOf(totalCount) + " Orders");
            orders.setForeground(Color.decode("#876900"));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public final void StyleFrame(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.plaf.basic.BasicInternalFrameUI ui =
            (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
    
    public void disp(){
        String stat = (String) status.getSelectedItem();
        String search = (String) searchBox.getSelectedItem();
        
        if(search.equals("Order ID")){
            search = "order_id";
        }else if (search.equals("Product ID")) {
            search = "prod_id";
        }else if (search.equals("User ID")) {
            search = "user_id";
        }
        
        DisplayTable table = new DisplayTable(stat, search, searchText.getText(), miniPanel);
        MainPane.remove(table);
        MainPane.add(table).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        orders = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        MainPane = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        searchBox = new javax.swing.JComboBox<>();
        pending = new javax.swing.JLabel();
        miniPanel = new javax.swing.JDesktopPane();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("ORDERS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(436, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(400, 400, 400))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 966, -1));

        orders.setBackground(new java.awt.Color(204, 204, 204));
        orders.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        orders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orders.setText("0 Order(s)");
        orders.setOpaque(true);
        getContentPane().add(orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 130, 39));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 130, 40));

        javax.swing.GroupLayout MainPaneLayout = new javax.swing.GroupLayout(MainPane);
        MainPane.setLayout(MainPaneLayout);
        MainPaneLayout.setHorizontalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        MainPaneLayout.setVerticalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(MainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 146, 500, 440));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REFRESH");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 117, 39));

        searchText.setEditable(false);
        searchText.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        searchText.setForeground(new java.awt.Color(204, 204, 204));
        searchText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchText.setText("Search User ID . . .");
        searchText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTextMouseClicked(evt);
            }
        });
        searchText.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                searchTextInputMethodTextChanged(evt);
            }
        });
        getContentPane().add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 160, 40));

        searchBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        searchBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBoxFocusLost(evt);
            }
        });
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });
        getContentPane().add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 150, 40));

        pending.setBackground(new java.awt.Color(204, 204, 204));
        pending.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        pending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pending.setText("0 Pending Order(s)");
        pending.setOpaque(true);
        getContentPane().add(pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 98, 179, 39));

        javax.swing.GroupLayout miniPanelLayout = new javax.swing.GroupLayout(miniPanel);
        miniPanel.setLayout(miniPanelLayout);
        miniPanelLayout.setHorizontalGroup(
            miniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        miniPanelLayout.setVerticalGroup(
            miniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(miniPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 430, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextMouseClicked
        animation ani = new animation();
        ani.addPlaceholder(searchText, s);        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextMouseClicked

    private void searchBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBoxFocusLost
        String selected = (String) searchBox.getSelectedItem();
        
        if(selected.equals("User ID")){
            searchText.setText("Search User ID . . .");
            s = "Search User ID . . .";
        }else if (selected.equals("Product ID")){
            searchText.setText("Search Product ID . . .");
            s = "Search Product ID . . .";
        }else if (selected.equals("Order ID")){
            searchText.setText("Search Order ID . . .");
            s = "Search Order ID . . .";
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBoxFocusLost

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        status.addActionListener(e -> disp());
        searchText.addKeyListener(new KeyAdapter() {
            public void FocusLost(KeyEvent e) {
                disp(); // refresh table as user types
            } 
        });// TODO add your handling code here:
    }//GEN-LAST:event_searchBoxActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        disp(); 
        countIndicators();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void searchTextInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_searchTextInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane MainPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane miniPanel;
    private javax.swing.JLabel orders;
    private javax.swing.JLabel pending;
    private javax.swing.JComboBox<String> searchBox;
    private javax.swing.JTextField searchText;
    private javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
