/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

/**
 *
 * @author user
 */
public class terms extends javax.swing.JFrame {

    /**
     * Creates new form terms
     */
    public terms() {
        initComponents();
        ShowTerms();
    }
    
    public void ShowTerms() {
    
    area.setText(
        "TERMS OF USE AND LEGAL LIABILITY\n\n" +

        "This section defines the legal responsibilities and liabilities associated " +
        "with the use, handling, and acquisition of regulated products within this system. " +
        "By proceeding, the user acknowledges full accountability for any actions performed " +
        "through their account.\n\n" +

        "1. PRODUCT ORIGIN AND TRACEABILITY\n" +
        "All regulated products, including firearms and related materials, are registered " +
        "and traceable to their original manufacturer, distributor, or legal owner. Each " +
        "transaction is recorded to ensure transparency and accountability throughout the " +
        "product lifecycle.\n\n" +

        "2. LIABILITY FOR MISUSE\n" +
        "Any misuse, illegal handling, or unauthorized deployment of the products obtained " +
        "through this system will result in severe legal consequences. The original source, " +
        "manufacturer, or authorized distributor of the firearm reserves the full right to " +
        "file legal action against the responsible user.\n\n" +

        "3. LEGAL ACTION AND PENALTIES\n" +
        "In the event of misuse, criminal negligence, or unlawful activity involving the " +
        "product, the user may face multiple charges under applicable laws. Legal actions " +
        "filed by the origin or authorized parties may significantly increase the severity " +
        "of penalties, including extended imprisonment, fines, and permanent disqualification " +
        "from ownership or access to regulated items.\n\n" +

        "4. USER ACCOUNTABILITY\n" +
        "The registered user is solely responsible for ensuring that all activities involving " +
        "the product remain lawful and within the scope of their authorization. Claiming lack " +
        "of knowledge or unauthorized use by third parties does not exempt the user from legal " +
        "responsibility.\n\n" +

        "5. ENFORCEMENT AND COOPERATION\n" +
        "This system fully cooperates with law enforcement agencies and authorized entities. " +
        "All necessary records, including transaction history and user information, may be " +
        "provided to support investigations and legal proceedings when required.\n\n" +

        "FINAL DECLARATION\n" +
        "By continuing to use this system, you acknowledge that any misuse of regulated " +
        "products may lead to legal action not only from government authorities but also " +
        "from the original source or distributor. Such actions may result in increased " +
        "legal penalties, including longer imprisonment and additional sanctions.\n\n" +

        "You agree to use all products responsibly, lawfully, and within the limits of " +
        "your authorization." +
            
        "By: ARMEX INCOORPORATION"
    );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area.setEditable(false);
        area.setColumns(20);
        area.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        area.setLineWrap(true);
        area.setRows(5);
        area.setWrapStyleWord(true);
        jScrollPane1.setViewportView(area);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BACK");
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(terms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new terms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
