/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import javax.swing.JComboBox;

/**
 *
 * @author user
 */
public class User_config {
    public void loadAllCountries(JComboBox<String> countryCombo) {
    countryCombo.removeAllItems();
    
    countryCombo.addItem("Select Country");
    countryCombo.addItem("Afghanistan");
    countryCombo.addItem("Albania");
    countryCombo.addItem("Algeria");
    countryCombo.addItem("Andorra");
    countryCombo.addItem("Angola");
    countryCombo.addItem("Antigua and Barbuda");
    countryCombo.addItem("Argentina");
    countryCombo.addItem("Armenia");
    countryCombo.addItem("Australia");
    countryCombo.addItem("Austria");
    countryCombo.addItem("Azerbaijan");
    countryCombo.addItem("Bahamas");
    countryCombo.addItem("Bahrain");
    countryCombo.addItem("Bangladesh");
    countryCombo.addItem("Barbados");
    countryCombo.addItem("Belarus");
    countryCombo.addItem("Belgium");
    countryCombo.addItem("Belize");
    countryCombo.addItem("Benin");
    countryCombo.addItem("Bhutan");
    countryCombo.addItem("Bolivia");
    countryCombo.addItem("Bosnia and Herzegovina");
    countryCombo.addItem("Botswana");
    countryCombo.addItem("Brazil");
    countryCombo.addItem("Brunei Darussalam");
    countryCombo.addItem("Bulgaria");
    countryCombo.addItem("Burkina Faso");
    countryCombo.addItem("Burundi");
    countryCombo.addItem("Cambodia");
    countryCombo.addItem("Cameroon");
    countryCombo.addItem("Canada");
    countryCombo.addItem("Cape Verde");
    countryCombo.addItem("Central African Republic");
    countryCombo.addItem("Chad");
    countryCombo.addItem("Chile");
    countryCombo.addItem("China");
    countryCombo.addItem("Colombia");
    countryCombo.addItem("Comoros");
    countryCombo.addItem("Congo, Democratic Republic of the");
    countryCombo.addItem("Congo, Republic of the");
    countryCombo.addItem("Costa Rica");
    countryCombo.addItem("Cote d'Ivoire");
    countryCombo.addItem("Croatia");
    countryCombo.addItem("Cuba");
    countryCombo.addItem("Cyprus");
    countryCombo.addItem("Czechia");
    countryCombo.addItem("Denmark");
    countryCombo.addItem("Djibouti");
    countryCombo.addItem("Dominica");
    countryCombo.addItem("Dominican Republic");
    countryCombo.addItem("Ecuador");
    countryCombo.addItem("Egypt");
    countryCombo.addItem("El Salvador");
    countryCombo.addItem("Equatorial Guinea");
    countryCombo.addItem("Eritrea");
    countryCombo.addItem("Estonia");
    countryCombo.addItem("Eswatini");
    countryCombo.addItem("Ethiopia");
    countryCombo.addItem("Fiji");
    countryCombo.addItem("Finland");
    countryCombo.addItem("France");
    countryCombo.addItem("Gabon");
    countryCombo.addItem("Gambia");
    countryCombo.addItem("Georgia");
    countryCombo.addItem("Germany");
    countryCombo.addItem("Ghana");
    countryCombo.addItem("Greece");
    countryCombo.addItem("Grenada");
    countryCombo.addItem("Guatemala");
    countryCombo.addItem("Guinea");
    countryCombo.addItem("Guinea-Bissau");
    countryCombo.addItem("Guyana");
    countryCombo.addItem("Haiti");
    countryCombo.addItem("Honduras");
    countryCombo.addItem("Hungary");
    countryCombo.addItem("Iceland");
    countryCombo.addItem("India");
    countryCombo.addItem("Indonesia");
    countryCombo.addItem("Iran");
    countryCombo.addItem("Iraq");
    countryCombo.addItem("Ireland");
    countryCombo.addItem("Israel");
    countryCombo.addItem("Italy");
    countryCombo.addItem("Jamaica");
    countryCombo.addItem("Japan");
    countryCombo.addItem("Jordan");
    countryCombo.addItem("Kazakhstan");
    countryCombo.addItem("Kenya");
    countryCombo.addItem("Kiribati");
    countryCombo.addItem("Kosovo");
    countryCombo.addItem("Kuwait");
    countryCombo.addItem("Kyrgyzstan");
    countryCombo.addItem("Laos");
    countryCombo.addItem("Latvia");
    countryCombo.addItem("Lebanon");
    countryCombo.addItem("Lesotho");
    countryCombo.addItem("Liberia");
    countryCombo.addItem("Libya");
    countryCombo.addItem("Liechtenstein");
    countryCombo.addItem("Lithuania");
    countryCombo.addItem("Luxembourg");
    countryCombo.addItem("Madagascar");
    countryCombo.addItem("Malawi");
    countryCombo.addItem("Malaysia");
    countryCombo.addItem("Maldives");
    countryCombo.addItem("Mali");
    countryCombo.addItem("Malta");
    countryCombo.addItem("Marshall Islands");
    countryCombo.addItem("Mauritania");
    countryCombo.addItem("Mauritius");
    countryCombo.addItem("Mexico");
    countryCombo.addItem("Micronesia, Federated States of");
    countryCombo.addItem("Moldova");
    countryCombo.addItem("Monaco");
    countryCombo.addItem("Mongolia");
    countryCombo.addItem("Montenegro");
    countryCombo.addItem("Morocco");
    countryCombo.addItem("Mozambique");
    countryCombo.addItem("Myanmar");
    countryCombo.addItem("Namibia");
    countryCombo.addItem("Nauru");
    countryCombo.addItem("Nepal");
    countryCombo.addItem("Netherlands");
    countryCombo.addItem("New Zealand");
    countryCombo.addItem("Nicaragua");
    countryCombo.addItem("Niger");
    countryCombo.addItem("Nigeria");
    countryCombo.addItem("North Korea");
    countryCombo.addItem("North Macedonia");
    countryCombo.addItem("Norway");
    countryCombo.addItem("Oman");
    countryCombo.addItem("Pakistan");
    countryCombo.addItem("Palau");
    countryCombo.addItem("Palestine");
    countryCombo.addItem("Panama");
    countryCombo.addItem("Papua New Guinea");
    countryCombo.addItem("Paraguay");
    countryCombo.addItem("Peru");
    countryCombo.addItem("Philippines");
    countryCombo.addItem("Poland");
    countryCombo.addItem("Portugal");
    countryCombo.addItem("Qatar");
    countryCombo.addItem("Romania");
    countryCombo.addItem("Russia");
    countryCombo.addItem("Rwanda");
    countryCombo.addItem("Saint Kitts and Nevis");
    countryCombo.addItem("Saint Lucia");
    countryCombo.addItem("Saint Vincent and the Grenadines");
    countryCombo.addItem("Samoa");
    countryCombo.addItem("San Marino");
    countryCombo.addItem("Sao Tome and Principe");
    countryCombo.addItem("Saudi Arabia");
    countryCombo.addItem("Senegal");
    countryCombo.addItem("Serbia");
    countryCombo.addItem("Seychelles");
    countryCombo.addItem("Sierra Leone");
    countryCombo.addItem("Singapore");
    countryCombo.addItem("Slovakia");
    countryCombo.addItem("Slovenia");
    countryCombo.addItem("Solomon Islands");
    countryCombo.addItem("Somalia");
    countryCombo.addItem("South Africa");
    countryCombo.addItem("South Korea");
    countryCombo.addItem("South Sudan");
    countryCombo.addItem("Spain");
    countryCombo.addItem("Sri Lanka");
    countryCombo.addItem("Sudan");
    countryCombo.addItem("Suriname");
    countryCombo.addItem("Sweden");
    countryCombo.addItem("Switzerland");
    countryCombo.addItem("Syria");
    countryCombo.addItem("Taiwan");
    countryCombo.addItem("Tajikistan");
    countryCombo.addItem("Tanzania");
    countryCombo.addItem("Thailand");
    countryCombo.addItem("Timor-Leste");
    countryCombo.addItem("Togo");
    countryCombo.addItem("Tonga");
    countryCombo.addItem("Trinidad and Tobago");
    countryCombo.addItem("Tunisia");
    countryCombo.addItem("Turkey");
    countryCombo.addItem("Turkmenistan");
    countryCombo.addItem("Tuvalu");
    countryCombo.addItem("Uganda");
    countryCombo.addItem("Ukraine");
    countryCombo.addItem("United Arab Emirates");
    countryCombo.addItem("United Kingdom");
    countryCombo.addItem("United States of America");
    countryCombo.addItem("Uruguay");
    countryCombo.addItem("Uzbekistan");
    countryCombo.addItem("Vanuatu");
    countryCombo.addItem("Vatican City");
    countryCombo.addItem("Venezuela");
    countryCombo.addItem("Vietnam");
    countryCombo.addItem("Yemen");
    countryCombo.addItem("Zambia");
    countryCombo.addItem("Zimbabwe");
}


}
