/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.Logs;

import Admin.Admin_config;
import com.toedter.calendar.JDateChooser;
import configuration.animation;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class Logs extends javax.swing.JInternalFrame {

    /**
     * Creates new form Logs
     */
    public Logs() {
        Admin_config admin = new Admin_config();
        
        initComponents();
        StyleFrame();
        admin.DisplayLogAction(actionBox);
        ShowTable();
    }
    
    private void ShowTable(){
        MainPane.removeAll();
        
        String s = logSearch.getText();
        String a = String.valueOf(actionBox.getSelectedItem());
        String to = ToField.getText();
        String from = FromField.getText();
        
        LogTable table = new LogTable(s, a, from, to);
        MainPane.add(table).setVisible(true);
    }
    
    public final void StyleFrame(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.plaf.basic.BasicInternalFrameUI ui =
            (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
    
    private Date selectedFromDate;
    private Date selectedToDate;
    private JButton openDateBtn;
    
    public Date getSelectedFromBirthdate() {
        return selectedFromDate;
    }
    public Date getSelectedToBirthdate() {
        return selectedToDate;
    }
    
    private void OpenDateDialogFrom() {
        JFrame frame = new JFrame();

        JDialog dialog = new JDialog(frame, "Select From Date", true);

        JDateChooser chooser = new JDateChooser();
        chooser.setDateFormatString("yyyy-MM-dd");
        chooser.setMaxSelectableDate(new Date()); // can't pick future date

        JButton okBtn = new JButton("OK");
        okBtn.addActionListener((ActionEvent e) -> {
            selectedFromDate = chooser.getDate();
            if (selectedFromDate != null) {
                // Format the date however you want
                String formattedDate = new SimpleDateFormat("dd / MM / yyyy").format(selectedFromDate);
                FromField.setText(formattedDate);
            }
            dialog.dispose();
        });

        dialog.setLayout(new BoxLayout(dialog.getContentPane(), BoxLayout.Y_AXIS));
        dialog.add(chooser);
        dialog.add(okBtn);

        dialog.pack();
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
    }
    
    public void OpenDateDialogTo(){
        JFrame frame = new JFrame();

        JDialog dialog = new JDialog(frame, "Select From Date", true);

        JDateChooser chooser = new JDateChooser();
        chooser.setDateFormatString("yyyy-MM-dd");
        chooser.setMaxSelectableDate(new Date()); // can't pick future date

        JButton okBtn = new JButton("OK");
        okBtn.addActionListener((ActionEvent e) -> {
            selectedToDate = chooser.getDate();
            if (selectedToDate != null) {
                // Format the date however you want
                String formattedDate = new SimpleDateFormat("dd / MM / yyyy").format(selectedToDate);
                ToField.setText(formattedDate);
            }
            dialog.dispose();
        });

        dialog.setLayout(new BoxLayout(dialog.getContentPane(), BoxLayout.Y_AXIS));
        dialog.add(chooser);
        dialog.add(okBtn);

        dialog.pack();
        dialog.setLocationRelativeTo(frame);
        dialog.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logSearch = new javax.swing.JTextField();
        FromField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ToField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        actionBox = new javax.swing.JComboBox<>();
        MainPane = new javax.swing.JDesktopPane();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("LOGS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(429, 429, 429)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logSearch.setEditable(false);
        logSearch.setForeground(new java.awt.Color(204, 204, 204));
        logSearch.setText("Search . . .");
        logSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logSearchMouseClicked(evt);
            }
        });
        jPanel2.add(logSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 336, 34));

        FromField.setEditable(false);
        FromField.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        FromField.setText("Current");
        FromField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FromFieldMouseClicked(evt);
            }
        });
        jPanel2.add(FromField, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 17, 132, 33));

        jLabel2.setText("From:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 23, -1, -1));

        jLabel3.setText("To:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 23, -1, -1));

        ToField.setEditable(false);
        ToField.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        ToField.setText("Current");
        ToField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToFieldMouseClicked(evt);
            }
        });
        jPanel2.add(ToField, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 16, 125, 34));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SEARCH");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 16, 102, 33));

        actionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(actionBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 16, 97, 34));

        javax.swing.GroupLayout MainPaneLayout = new javax.swing.GroupLayout(MainPane);
        MainPane.setLayout(MainPaneLayout);
        MainPaneLayout.setHorizontalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MainPaneLayout.setVerticalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addComponent(MainPane, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(MainPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FromFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FromFieldMouseClicked
        OpenDateDialogFrom();        // TODO add your handling code here:
    }//GEN-LAST:event_FromFieldMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        ShowTable();                // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void logSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logSearchMouseClicked
        animation ani =  new animation();

        ani.addPlaceholder(logSearch, "Search . . .");     // TODO add your handling code here:
    }//GEN-LAST:event_logSearchMouseClicked

    private void ToFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToFieldMouseClicked
        OpenDateDialogTo();        // TODO add your handling code here:
    }//GEN-LAST:event_ToFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FromField;
    private javax.swing.JDesktopPane MainPane;
    private javax.swing.JTextField ToField;
    private javax.swing.JComboBox<String> actionBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField logSearch;
    // End of variables declaration//GEN-END:variables
}
