/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.Logs;

import configuration.config;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 *
 * @author user
 */
public class LogTable extends javax.swing.JInternalFrame {

    /**
     * Creates new form LogTable
     */
    private String search;
    private String act;
    private String From;
    private String To;
    
    
    public LogTable(String searchText, String action, String FromDate, String ToDate) {
        initComponents();
        StyleFrame();
        
        this.search = searchText;
        this.act = action;
        this.From = FromDate;
        this.To = ToDate;
        
        ShowTable();
    }
    
    public void ShowTable() {
    config conf = new config();

    String searchText = search != null ? search.trim() : "";
    String actionFilter = act != null ? act.trim() : "";
    String fromStr = From != null ? From.trim() : "";
    String toStr = To != null ? To.trim() : "";

    StringBuilder qry = new StringBuilder("SELECT * FROM logs WHERE 1=1 ");
    List<Object> params = new ArrayList<>();

    // Filter by log_action if not empty
    if (!actionFilter.isEmpty() && !actionFilter.equalsIgnoreCase("All")) {
        qry.append("AND LOWER(log_action) = LOWER(?) ");
        params.add(actionFilter);
    }
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd / MM / yyyy");

    // Filter by From/To date if provided
    try {
        if (!fromStr.isEmpty() && !fromStr.equalsIgnoreCase("Current")) {
            // Use only the date part
            java.util.Date fromDate = sdf.parse(fromStr);
            String fromDateStr = new SimpleDateFormat("yyyy-MM-dd").format(fromDate);
            qry.append("AND DATE(dateTime) >= ? ");
            params.add(fromDateStr);
        }
        if (!toStr.isEmpty() && !toStr.equalsIgnoreCase("Current")) {
            java.util.Date toDate = sdf.parse(toStr);
            String toDateStr = new SimpleDateFormat("yyyy-MM-dd").format(toDate);
            qry.append("AND DATE(dateTime) <= ? ");
            params.add(toDateStr);
        }
    } catch (ParseException e) {
        e.printStackTrace();
    }

    // Search logic: numeric → log_id, otherwise text match for log_action
    if (!searchText.isEmpty() && !searchText.equalsIgnoreCase("Search Products . . .")) {
        try {
            int idSearch = Integer.parseInt(searchText);
            qry.append("ORDER BY CASE WHEN log_id = ? THEN 0 ELSE 1 END, dateTime DESC");
            params.add(idSearch);
        } catch (NumberFormatException e) {
            qry.append("ORDER BY CASE WHEN LOWER(log_action) LIKE LOWER(?) THEN 0 ELSE 1 END, dateTime DESC");
            params.add("%" + searchText + "%");
        }
    } else {
        qry.append("ORDER BY dateTime DESC");
    }

    // Execute query
    conf.displayData(qry.toString(), table, params.toArray());
}
    
    public final void StyleFrame(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.plaf.basic.BasicInternalFrameUI ui =
            (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
