/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.UserControl;

import Admin.ProductControl.Edit_Product;
import configuration.LogReg_config;
import configuration.Validations;
import configuration.animation;
import configuration.config;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author user
 */
public final class Add_user extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_user
     */
    public Add_user() {
        initComponents();
        BtnToggles();
        StyleFrame();
    }
    
    public void BtnToggles(){
        ButtonGroup menuGroup = new ButtonGroup();
        
        menuGroup.add(user);
        menuGroup.add(admin);
        menuGroup.add(driver);
        
        animation.StyleToggleButtons(user); 
        animation.StyleToggleButtons(admin); 
        animation.StyleToggleButtons(driver); 
        animation.StyleToggleButtons(ussageToggle); 
        animation.StyleToggleButtons(sysacc); 
    }
    
    public final void StyleFrame(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.plaf.basic.BasicInternalFrameUI ui =
            (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
    
    public final void GetInputs(){
        LogReg_config conf = new LogReg_config();
        String access = "null";
        String acc = "null";
        
        String nm = name4.getText();
        String bdg = badge4.getText();
        String ps = pass4.getText();
        String ussage = ussageToggle.getText();
        
        
        if(user.isSelected()){
            access = "User";
        }else if(admin.isSelected()){
            access = "Admin";
        }else if(driver.isSelected()){
            access = "Dispatcher";
        }
        
        if(sysacc.isSelected()){
            acc = "open";
        }
       
        conf.RegisterByAdmin(nm, bdg, ps, access, ussage, acc);
        
        EraseText();
    }
        
    Border grayBorder = BorderFactory.createLineBorder(Color.GRAY, 2);
    Border orangeBorder = BorderFactory.createLineBorder(Color.ORANGE, 2);
    Border greenBorder = BorderFactory.createLineBorder(Color.GREEN, 2);
    Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);
    
    private void ChangeBarLabel(int value){   
        
        passStrength4.setOpaque(true);
        passStrength4.setBorderPainted(false);
        passStrength4.setUI(new javax.swing.plaf.basic.BasicProgressBarUI());
        passStrength4.setBackground(Color.LIGHT_GRAY);
        
        if(value <= 10 && value >= 1){
            PassLabel4.setText("Poor");
            PassLabel4.setForeground(new Color(204,0,51));
            passStrength4.setForeground(new Color(153,0,0));
        }else if(value <= 30 && value >= 11){
            PassLabel4.setText("Low");
            PassLabel4.setForeground(new Color(255,153,0));
            passStrength4.setForeground(new Color(255,153,0));
        }else if(value <= 50 && value >= 31){
            PassLabel4.setText("Good");
            PassLabel4.setForeground(new Color(255,255,0));
            passStrength4.setForeground(new Color(255,255,51));
        }else if(value <= 75 && value >= 51){
            PassLabel4.setText("Perfect");
            PassLabel4.setForeground(new Color(204,255,204));
            passStrength4.setForeground(new Color(0,255,0));
        }else if(value <= 99 && value >= 76){
            PassLabel4.setText("Excellent");
            PassLabel4.setForeground(new Color(0,204,51));
            passStrength4.setForeground(new Color(153,255,204));
        }else if(value == 100){
            PassLabel4.setText("Unique");
            PassLabel4.setForeground(new Color(102,102,255));
            passStrength4.setForeground(new Color(153,153,255));
        }else{
            PassLabel4.setText("Vulnerable");
            PassLabel4.setForeground(new Color(204,204,204));
            passStrength4.setForeground(new Color(204,204,204));
        }
    }
    
    public void EraseText(){
        user.setSelected(true);
        admin.setSelected(false);
        name4.setText("Username");
        badge4.setText("Badge");
        pass4.setText("Password");
        
        ussageToggle.setSelected(false);
        ussageToggle.setText("Disable");
        
        name4.setBorder(grayBorder);
        badge4.setBorder(grayBorder);
        pass4.setBorder(grayBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        name4 = new javax.swing.JTextField();
        pass4 = new javax.swing.JTextField();
        badge4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        PassLabel4 = new javax.swing.JLabel();
        passStrength4 = new javax.swing.JProgressBar();
        jPanel16 = new javax.swing.JPanel();
        user = new javax.swing.JToggleButton();
        admin = new javax.swing.JToggleButton();
        jLabel31 = new javax.swing.JLabel();
        driver = new javax.swing.JToggleButton();
        jPanel17 = new javax.swing.JPanel();
        ussageToggle = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sysacc = new javax.swing.JToggleButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("---------------------------------------------------------------");
        jLabel27.setToolTipText("");
        jLabel27.setAutoscrolls(true);
        jPanel15.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 389, 380, -1));

        name4.setEditable(false);
        name4.setBackground(new java.awt.Color(255, 255, 255));
        name4.setForeground(new java.awt.Color(153, 153, 153));
        name4.setText("Username");
        name4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name4MouseClicked(evt);
            }
        });
        name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name4ActionPerformed(evt);
            }
        });
        name4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name4KeyReleased(evt);
            }
        });
        jPanel15.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 188, 44));

        pass4.setEditable(false);
        pass4.setBackground(new java.awt.Color(255, 255, 255));
        pass4.setForeground(new java.awt.Color(153, 153, 153));
        pass4.setText("Password");
        pass4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass4MouseClicked(evt);
            }
        });
        pass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass4ActionPerformed(evt);
            }
        });
        pass4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass4KeyReleased(evt);
            }
        });
        jPanel15.add(pass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 99, 375, 44));

        badge4.setEditable(false);
        badge4.setBackground(new java.awt.Color(255, 255, 255));
        badge4.setForeground(new java.awt.Color(153, 153, 153));
        badge4.setText("Badge");
        badge4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badge4MouseClicked(evt);
            }
        });
        badge4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badge4ActionPerformed(evt);
            }
        });
        badge4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                badge4KeyReleased(evt);
            }
        });
        jPanel15.add(badge4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 46, 183, 44));

        jLabel29.setText("Account password strength: ");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 369, -1, -1));

        PassLabel4.setBackground(new java.awt.Color(153, 153, 153));
        PassLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PassLabel4.setForeground(new java.awt.Color(204, 204, 204));
        PassLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassLabel4.setText("Null");
        PassLabel4.setOpaque(true);
        jPanel15.add(PassLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 369, 170, -1));

        passStrength4.setForeground(new java.awt.Color(204, 204, 204));
        passStrength4.setOpaque(true);
        jPanel15.add(passStrength4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 339, 375, -1));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setSelected(true);
        user.setText("USER");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel16.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        admin.setText("ADMIN");
        jPanel16.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, -1));

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel31.setText("ACCESS");
        jPanel16.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        driver.setText("DISPATCHER");
        jPanel16.add(driver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 150, 185, 180));

        ussageToggle.setText("Disable");
        ussageToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ussageToggleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel1.setText("USSAGE");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ussageToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ussageToggle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 153, -1, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONFIRM");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel15.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 220, 40));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RESET");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel15.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 80, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("ADD USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 410, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel4.setText("SYSTEM ACCESS");

        sysacc.setSelected(true);
        sysacc.setText("OPEN");
        sysacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sysaccMouseClicked(evt);
            }
        });
        sysacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysaccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sysacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sysacc)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel15.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 90));

        getContentPane().add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name4MouseClicked
        animation ani = new animation();

        ani.addPlaceholder(name4, "Username");         // TODO add your handling code here:
    }//GEN-LAST:event_name4MouseClicked

    private void name4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name4ActionPerformed

    private void name4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name4KeyReleased
        animation ani = new animation();

        String nm = name4.getText();

        if(!nm.equals("Username")){
            ani.validateRequired(name4);
        }else if(nm.isEmpty()){
            name4.setBorder(grayBorder);
        }else{
            name4.setBorder(redBorder);
        }// TODO add your handling code here:
    }//GEN-LAST:event_name4KeyReleased

    private void pass4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass4MouseClicked
        animation ani = new animation();

        ani.addPlaceholder(pass4, "Password");         // TODO add your handling code here:
    }//GEN-LAST:event_pass4MouseClicked

    private void pass4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass4ActionPerformed

    private void pass4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass4KeyReleased
        animation ani = new animation();
        ani.validateRequired(pass4);

        pass4.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { updateStrength(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { updateStrength(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { updateStrength(); }

            private void updateStrength() {
                String password = pass4.getText();
                
                    if(!password.equals("Password")){
                    int strength = ani.calculatePasswordStrength(password, passStrength4);
                    ChangeBarLabel(strength);
                }
            }
        }); // TODO add your handling code here:
    }//GEN-LAST:event_pass4KeyReleased

    private void badge4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badge4MouseClicked
        animation ani = new animation();

        ani.addPlaceholder(badge4, "Badge");         // TODO add your handling code here:
    }//GEN-LAST:event_badge4MouseClicked

    private void badge4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badge4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badge4ActionPerformed

    private void badge4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_badge4KeyReleased
        animation ani = new animation();
        Validations validate = new Validations();

        String bdg = badge4.getText();

        int valid = validate.BadgeValidate(bdg);

        switch (valid) {
            case 1:
            ani.validateRequired(badge4);
            break;
            case 0:
            badge4.setBorder(redBorder);
            break;
            case 3:
            badge4.setBorder(orangeBorder);
            break;
            default:
            badge4.setBorder(grayBorder);
            break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_badge4KeyReleased

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void ussageToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ussageToggleActionPerformed
        if(ussageToggle.isSelected()){
            String ussage = "Enable";
            ussageToggle.setText("Enable");
        }else{
            String ussage = "Disable";
            ussageToggle.setText("Disable");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ussageToggleActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setBackground(new Color(102,102,102));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setBackground(new Color(153,153,153));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        GetInputs();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setBackground(new Color(102,102,102)); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setBackground(new Color(153,153,153));// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        EraseText();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void sysaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysaccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sysaccActionPerformed

    private void sysaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sysaccMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sysaccMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PassLabel4;
    private javax.swing.JToggleButton admin;
    private javax.swing.JTextField badge4;
    private javax.swing.JToggleButton driver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name4;
    private javax.swing.JTextField pass4;
    private javax.swing.JProgressBar passStrength4;
    private javax.swing.JToggleButton sysacc;
    private javax.swing.JToggleButton user;
    private javax.swing.JToggleButton ussageToggle;
    // End of variables declaration//GEN-END:variables
}
