/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.UserControl;

import configuration.LogReg_config;
import configuration.Validations;
import configuration.animation;
import configuration.config;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.border.Border;

/**
 *
 * @author user
 */
public final class Add_user extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_user
     */
    public Add_user() {
        initComponents();
        BtnToggles();
        StyleFrame();
    }
    
    public void BtnToggles(){
        ButtonGroup menuGroup = new ButtonGroup();
        
        menuGroup.add(user);
        menuGroup.add(admin);
        
        animation.StyleToggleButtons(user); 
        animation.StyleToggleButtons(admin); 
        animation.StyleToggleButtons(ussageToggle); 
    }
    
    public void StyleFrame(){
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }
    
    public final void GetInputs(){
        LogReg_config conf = new LogReg_config();
        String access = "null";
        
        String nm = name4.getText();
        String bdg = badge4.getText();
        String ps = pass4.getText();
        String ussage = ussageToggle.getText();
        
        if(user.isSelected()){
            access = "User";
        }else if(admin.isSelected()){
            access = "Admin";
        }
       
        conf.RegisterByAdmin(nm, bdg, ps, access, ussage);
        
    }
        
    Border grayBorder = BorderFactory.createLineBorder(Color.GRAY, 2);
    Border orangeBorder = BorderFactory.createLineBorder(Color.ORANGE, 2);
    Border greenBorder = BorderFactory.createLineBorder(Color.GREEN, 2);
    Border redBorder = BorderFactory.createLineBorder(Color.RED, 2);
    
    private void ChangeBarLabel(int value){   
        
        passStrength4.setOpaque(true);
        passStrength4.setBorderPainted(false);
        passStrength4.setUI(new javax.swing.plaf.basic.BasicProgressBarUI());
        passStrength4.setBackground(Color.LIGHT_GRAY);
        
        if(value <= 10 && value >= 1){
            PassLabel4.setText("Poor");
            PassLabel4.setForeground(new Color(204,0,51));
            passStrength4.setForeground(new Color(153,0,0));
        }else if(value <= 30 && value >= 11){
            PassLabel4.setText("Low");
            PassLabel4.setForeground(new Color(255,153,0));
            passStrength4.setForeground(new Color(255,153,0));
        }else if(value <= 50 && value >= 31){
            PassLabel4.setText("Good");
            PassLabel4.setForeground(new Color(255,255,0));
            passStrength4.setForeground(new Color(255,255,51));
        }else if(value <= 75 && value >= 51){
            PassLabel4.setText("Perfect");
            PassLabel4.setForeground(new Color(204,255,204));
            passStrength4.setForeground(new Color(0,255,0));
        }else if(value <= 99 && value >= 76){
            PassLabel4.setText("Excellent");
            PassLabel4.setForeground(new Color(0,204,51));
            passStrength4.setForeground(new Color(153,255,204));
        }else if(value == 100){
            PassLabel4.setText("Unique");
            PassLabel4.setForeground(new Color(102,102,255));
            passStrength4.setForeground(new Color(153,153,255));
        }else{
            PassLabel4.setText("Vulnerable");
            PassLabel4.setForeground(new Color(204,204,204));
            passStrength4.setForeground(new Color(204,204,204));
        }
    }
    
    public void EraseText(){
        user.setSelected(true);
        admin.setSelected(false);
        name4.setText("Username");
        badge4.setText("Badge");
        pass4.setText("Password");
        
        ussageToggle.setSelected(false);
        ussageToggle.setText("Disable");
        
        name4.setBorder(grayBorder);
        badge4.setBorder(grayBorder);
        pass4.setBorder(grayBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        name4 = new javax.swing.JTextField();
        pass4 = new javax.swing.JTextField();
        badge4 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        PassLabel4 = new javax.swing.JLabel();
        passStrength4 = new javax.swing.JProgressBar();
        jLabel30 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        user = new javax.swing.JToggleButton();
        admin = new javax.swing.JToggleButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        ussageToggle = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("------------------------------------------------------------------------------------------------------------------------------");
        jPanel15.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("ADD USER");
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 16, -1, -1));

        name4.setEditable(false);
        name4.setBackground(new java.awt.Color(204, 204, 204));
        name4.setForeground(new java.awt.Color(153, 153, 153));
        name4.setText("Username");
        name4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name4MouseClicked(evt);
            }
        });
        name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name4ActionPerformed(evt);
            }
        });
        name4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name4KeyReleased(evt);
            }
        });
        jPanel15.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 46, 183, 44));

        pass4.setEditable(false);
        pass4.setBackground(new java.awt.Color(204, 204, 204));
        pass4.setForeground(new java.awt.Color(153, 153, 153));
        pass4.setText("Password");
        pass4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass4MouseClicked(evt);
            }
        });
        pass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass4ActionPerformed(evt);
            }
        });
        pass4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass4KeyReleased(evt);
            }
        });
        jPanel15.add(pass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 99, 370, 44));

        badge4.setEditable(false);
        badge4.setBackground(new java.awt.Color(204, 204, 204));
        badge4.setForeground(new java.awt.Color(153, 153, 153));
        badge4.setText("Badge");
        badge4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badge4MouseClicked(evt);
            }
        });
        badge4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badge4ActionPerformed(evt);
            }
        });
        badge4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                badge4KeyReleased(evt);
            }
        });
        jPanel15.add(badge4, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 46, 183, 44));

        jLabel29.setText("Account password strength: ");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        PassLabel4.setBackground(new java.awt.Color(153, 153, 153));
        PassLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        PassLabel4.setForeground(new java.awt.Color(204, 204, 204));
        PassLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PassLabel4.setText("Null");
        PassLabel4.setOpaque(true);
        jPanel15.add(PassLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 166, -1));

        passStrength4.setForeground(new java.awt.Color(204, 204, 204));
        passStrength4.setOpaque(true);
        jPanel15.add(passStrength4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 380, -1));

        jLabel30.setBackground(new java.awt.Color(153, 153, 153));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("CONFIRM");
        jLabel30.setToolTipText("");
        jLabel30.setOpaque(true);
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        jPanel15.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 237, 183, 38));

        user.setSelected(true);
        user.setText("USER");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        admin.setText("ADMIN");

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel31.setText("ACCESS");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(1, 1, 1)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user)
                    .addComponent(admin))
                .addGap(1, 1, 1))
        );

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 380, 60));

        ussageToggle.setText("Disable");
        ussageToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ussageToggleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel1.setText("USSAGE");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ussageToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(59, 59, 59))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ussageToggle)
                .addContainerGap())
        );

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 190, 90));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONFIRM");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel15.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 220, 40));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RESET");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel15.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 80, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name4MouseClicked
        animation ani = new animation();

        ani.addPlaceholder(name4, "Username");         // TODO add your handling code here:
    }//GEN-LAST:event_name4MouseClicked

    private void name4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name4ActionPerformed

    private void name4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name4KeyReleased
        animation ani = new animation();

        String nm = name4.getText();

        if(!nm.equals("Username")){
            ani.validateRequired(name4);
        }else{
            name4.setBorder(redBorder);
        }// TODO add your handling code here:
    }//GEN-LAST:event_name4KeyReleased

    private void pass4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass4MouseClicked
        animation ani = new animation();

        ani.addPlaceholder(pass4, "Password");         // TODO add your handling code here:
    }//GEN-LAST:event_pass4MouseClicked

    private void pass4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass4ActionPerformed

    private void pass4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass4KeyReleased
        animation ani = new animation();
        ani.validateRequired(pass4);

        pass4.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) { updateStrength(); }
            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) { updateStrength(); }
            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) { updateStrength(); }

            private void updateStrength() {
                String password = pass4.getText();
                
                    if(!password.equals("Password")){
                    int strength = ani.calculatePasswordStrength(password, passStrength4);
                    ChangeBarLabel(strength);
                }
            }
        }); // TODO add your handling code here:
    }//GEN-LAST:event_pass4KeyReleased

    private void badge4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badge4MouseClicked
        animation ani = new animation();

        ani.addPlaceholder(badge4, "Badge");         // TODO add your handling code here:
    }//GEN-LAST:event_badge4MouseClicked

    private void badge4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badge4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badge4ActionPerformed

    private void badge4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_badge4KeyReleased
        animation ani = new animation();
        Validations validate = new Validations();

        String bdg = badge4.getText();

        int valid = validate.BadgeValidate(bdg);

        switch (valid) {
            case 1:
            ani.validateRequired(badge4);
            break;
            case 0:
            badge4.setBorder(redBorder);
            break;
            case 3:
            badge4.setBorder(orangeBorder);
            break;
            default:
            badge4.setBorder(grayBorder);
            break;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_badge4KeyReleased

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        LogReg_config logreg = new LogReg_config();

        String nm = name4.getText();
        String bdg = badge4.getText();
        String ps = pass4.getText();

        logreg.Register(nm, bdg, ps);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void ussageToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ussageToggleActionPerformed
        if(ussageToggle.isSelected()){
            String ussage = "Enable";
            ussageToggle.setText("Enable");
        }else{
            String ussage = "Disable";
            ussageToggle.setText("Disable");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ussageToggleActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setBackground(new Color(102,102,102));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setBackground(new Color(153,153,153));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        GetInputs();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setBackground(new Color(102,102,102)); // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setBackground(new Color(153,153,153));// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        EraseText();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PassLabel4;
    private javax.swing.JToggleButton admin;
    private javax.swing.JTextField badge4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JTextField name4;
    private javax.swing.JTextField pass4;
    private javax.swing.JProgressBar passStrength4;
    private javax.swing.JToggleButton user;
    private javax.swing.JToggleButton ussageToggle;
    // End of variables declaration//GEN-END:variables
}
