/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.UserControl;

import configuration.config;

/**
 *
 * @author user
 */
public class tableUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form tableUser
     */
    private static String txt;
    private static String stat;
    
    public tableUser(String status, String text) {
        this.txt = text;
        this.stat = status;
        
        initComponents();
        StyleFrame();
        DispTable();
        StyleTable();
    }
    
    public void StyleTable(){
        table.setRowHeight(50);
        
    }
    
    public void StyleFrame(){
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }
    
    public void DispTable() {
    config conf = new config();

    // Trim inputs to avoid whitespace issues
    String status = stat != null ? stat.trim() : "All";
    String text = txt != null ? txt.trim() : "";

    System.out.println("Status: " + status);
    System.out.println("Text: " + text);

    // Case 1: Show all users when default text or empty
    if (status.equals("All") && (text.isEmpty() || text.equalsIgnoreCase("Search Users . . ."))) {
        String qry = "SELECT * FROM users ORDER BY user_name";
        conf.displayData(qry, table);
        return;
    }

    try {
        // Try interpreting the text as a numeric user ID
        int id = Integer.parseInt(text);

        if (status.equals("All")) {
            String qry = "SELECT * FROM users ORDER BY CASE WHEN user_id = ? THEN 0 ELSE 1 END, user_name";
            conf.displayData(qry, table, id);
        } else {
            String qry = "SELECT * FROM users WHERE user_access = ? ORDER BY CASE WHEN user_id = ? THEN 0 ELSE 1 END, user_name";
            conf.displayData(qry, table, status, id);
        }

    } catch (NumberFormatException e) {
        // If text is not a number, do a name search
        if (status.equals("All")) {
            String qry = "SELECT * FROM users WHERE user_name LIKE ? ORDER BY user_name";
            conf.displayData(qry, table, "%" + text + "%");
        } else {
            String qry = "SELECT * FROM users WHERE user_access = ? AND user_name LIKE ? ORDER BY user_name";
            conf.displayData(qry, table, status, "%" + text + "%");
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
