/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin.ProductControl;

import Admin.Admin_config;
import configuration.config;
import javax.swing.JDesktopPane;

/**
 *
 * @author user
 */
public class tableProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form table
     */
    
    private static String stat;
    private static String txt;
    
    public tableProduct(String status, String text) {
        
        this.stat = status;
        this.txt = text;
        
        initComponents();
        StyleFrame();
        DispTable();
        StyleTable();
    }
    
    public void StyleTable(){
        table.setRowHeight(50);
        
    }
    
    public void StyleFrame(){
        this.setBorder(null);
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }
    
    public void RefreshTable(){
        
    }
    
    public void DispTable() {

    config conf = new config();

    String status = stat;
    String text = txt;

    System.out.println(status);
    System.out.println(text);


    if (status.equals("All") && 
        (text.equals("Search Products . . .") || text.trim().isEmpty())) {

        String qry = "SELECT * FROM products ORDER BY prod_name";
        conf.displayData(qry, table);
        return;
    }

    try {
        int id = Integer.parseInt(text);

        if (status.equals("All")) {

            String qry =
                "SELECT * FROM products " +
                "ORDER BY CASE " +
                "WHEN prod_id = ? THEN 0 " +
                "ELSE 1 END, prod_name";

            conf.displayData(qry, table, id);

        } else {

            String qry =
                "SELECT * FROM products " +
                "WHERE prod_status = ? " +
                "ORDER BY CASE " +
                "WHEN prod_id = ? THEN 0 " +
                "ELSE 1 END, prod_name";

            conf.displayData(qry, table, status, id);
        }

    } catch (NumberFormatException e) {

        if (text.equals("Search Products . . .") || text.trim().isEmpty()) {

            if (status.equals("All")) {
                String qry = "SELECT * FROM products ORDER BY prod_name";
                conf.displayData(qry, table);
            } else {
                String qry = "SELECT * FROM products WHERE prod_status = ? ORDER BY prod_name";
                conf.displayData(qry, table, status);
            }

        } else {

            if (status.equals("All")) {

                String qry =
                    "SELECT * FROM products " +
                    "ORDER BY CASE " +
                    "WHEN prod_name LIKE ? THEN 0 " +
                    "ELSE 1 END, prod_name";

                conf.displayData(qry, table, "%" + text + "%");

            } else {

                String qry =
                    "SELECT * FROM products " +
                    "WHERE prod_status = ? " +
                    "ORDER BY CASE " +
                    "WHEN prod_name LIKE ? THEN 0 " +
                    "ELSE 1 END, prod_name";

                conf.displayData(qry, table, status, "%" + text + "%");
            }
        }
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
