/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package about;

import configuration.animation;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class about extends javax.swing.JInternalFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
        ShowPanels();
        StyleFrame();
    }
    
    public final void StyleFrame(){
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.plaf.basic.BasicInternalFrameUI ui =
            (javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }
    
    public void ShowPanels(){
        jPanel2.setLayout(new GridBagLayout());
        jPanel3.setLayout(new GridBagLayout());
        jPanel4.setLayout(new GridBagLayout());
        
        jPanel2.setBackground(Color.WHITE);
        jPanel2.setBorder(BorderFactory.createLineBorder(new Color(33, 150, 243), 2));

        jPanel3.setBackground(Color.WHITE);
        jPanel3.setBorder(BorderFactory.createLineBorder(new Color(76, 175, 80), 2));

        jPanel4.setBackground(Color.WHITE);
        jPanel4.setBorder(BorderFactory.createLineBorder(new Color(255, 87, 34), 2));
        
        // For efficiency label
        effi.setFont(new Font("Segoe UI", Font.BOLD, 16)); // Bold font
        effi.setForeground(new Color(33, 150, 243));        // Blue color
        effi.setHorizontalAlignment(SwingConstants.CENTER); // Center text

        // For User Experience label
        UX.setFont(new Font("Segoe UI", Font.BOLD, 16));
        UX.setForeground(new Color(76, 175, 80));           // Green color
        UX.setHorizontalAlignment(SwingConstants.CENTER);

        // For User Interactive label
        UI.setFont(new Font("Segoe UI", Font.BOLD, 16));
        UI.setForeground(new Color(255, 87, 34));           // Orange color
        UI.setHorizontalAlignment(SwingConstants.CENTER);
        
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;  // allow horizontal expansion
        gbc.weighty = 1.0;  // allow vertical expansion
        gbc.fill = GridBagConstraints.BOTH; // fill the space
        gbc.insets = new Insets(10, 10, 10, 10); // padding around label

        // Efficiency panel
        effi.setText("<html>"
                + "<span style='font-size:18px; color:#1E88E5; font-weight:bold;'>EFFICIENCY</span><br>"
                + "<span style='font-size:13px; color:#555;'>Optimized performance for every task, ensuring your operations run smoothly and reliably.<br>"
                + "Fast processing ⚡, minimal downtime, and maximum productivity.<br>"
                + "Resource-efficient algorithms reduce memory usage and speed up execution.<br>"
                + "Continuous monitoring and smart optimization guarantee consistent results.</span>"
                + "</html>");
        jPanel2.add(effi, gbc);

        // User Experience panel
        UX.setText("<html>"
                + "<span style='font-size:18px; color:#43A047; font-weight:bold;'>User Experience</span><br>"
                + "<span style='font-size:13px; color:#555;'>Intuitive interface designed to simplify your workflow and reduce friction.<br>"
                + "Seamless navigation 🧭, clear instructions, and easy-to-access features improve overall satisfaction.<br>"
                + "Thoughtful layout ensures users find what they need quickly.<br>"
                + "Consistent design patterns reduce learning curve and enhance comfort.</span>"
                + "</html>");
        jPanel3.add(UX, gbc);

        // User Interactive panel
        UI.setText("<html>"
                + "<span style='font-size:18px; color:#F4511E; font-weight:bold;'>User Interactive</span><br>"
                + "<span style='font-size:13px; color:#555;'>Engaging interactions that respond to your input instantly.<br>"
                + "Responsive design 🎯, interactive elements, and visual feedback enhance the overall engagement experience.<br>"
                + "Animations and dynamic content create a lively interface.<br>"
                + "User-driven customization options allow a personalized and immersive experience.</span>"
                + "</html>");
        jPanel4.add(UI, gbc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        effi = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        UI = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        UX = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setText("ABOUT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(405, 405, 405))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 939, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        effi.setText("EFFICIENCY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(effi, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(effi, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 290, 520));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        UI.setText("User Interactive");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UI, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UI, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 300, 520));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        UX.setText("User Experince");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UX, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UX, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 290, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        animation ani = new animation();

        ani.transitionBackground(
            jPanel2,
            Color.decode("#FFFFFF"),
            Color.decode("#C7FFF9"),
            200 
        );    // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        animation ani = new animation();

        ani.transitionBackground(
            jPanel2,
            Color.decode("#C7FFF9"),
            Color.decode("#FFFFFF"),
            200 
        );         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        animation ani = new animation();

        ani.transitionBackground(
            jPanel4,
            Color.decode("#FFFFFF"),
            Color.decode("#FFC7C7"),
            200 
        );           // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        animation ani = new animation();

        ani.transitionBackground(
            jPanel4,
            Color.decode("#FFC7C7"),
            Color.decode("#FFFFFF"),
            200 
        );         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        animation ani = new animation();

        ani.transitionBackground(
            jPanel3,
            Color.decode("#FFFFFF"),
            Color.decode("#C7FFD0"),
            200 
        );           // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        animation ani = new animation();

        ani.transitionBackground(
            jPanel3,
            Color.decode("#C7FFD0"),
            Color.decode("#FFFFFF"),
            200 
        );         // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UI;
    private javax.swing.JLabel UX;
    private javax.swing.JLabel effi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
